name: 문서 작성 및 수정 요청
description: '문서 작업, 설정 수정, 의존성 업데이트 등의 관리 작업'
title: '[CHORE] 제목을 입력해주세요'
labels: [CHORE]
assignees:
  - jho951

body:
  - type: markdown
    attributes:
      value: |
        ### 설명
        ❗문서 작업이나 설정 수정, 의존성 업데이트 등 관리적인 작업에 대한 설명을 작성해 주세요.

  - type: input
    attributes:
      label: '작업 설명'
      description: '어떤 작업을 해야 하나요?'
      placeholder: '수정할 문서나 설정 파일, 의존성 등을 설명해주세요.'
      required: true

  - type: input
    attributes:
      label: '우선순위'
      description: '이 작업의 우선순위는 무엇인가요?'
      placeholder: '낮음, 중간, 높음'
      required: true

  - type: input
    attributes:
      label: '관련 이슈'
      description: '관련된 이슈 번호가 있나요? (예: #123)'
      placeholder: '예: #123'
      required: false
