name: Feature
description: 새로운 기능이나 개선 사항 제안 시 사용
title: "[FEATURE] 기능 제목을 입력해주세요"
labels: [FEATURE]
assignees:
  - jho951

body:
  - type: markdown
    attributes:
      value: |
        ### 설명
        ❗️ 작업한 기능을 작성해주세요.

  - type: textarea
    id: summary
    attributes:
      label: 기능 설명
      description: 어떤 기능을 제안하시나요?
      placeholder: 여기에 설명을 입력하세요
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 필요한 이유
      description: 왜 이 기능이 필요한가요?
      placeholder: 사용자의 요구나 문제점을 설명해주세요
    validations:
      required: true

  - type: input
    id: reference
    attributes:
      label: 참고 자료
      description: 관련 문서나 링크가 있다면 적어주세요
      placeholder: https://...
    validations:
      required: false