name: 유지보수 요청
description: 유지보수나 리팩토링 작업 시 사용
title: "[REFACTOR] 제목을 입력해주세요"
labels: [REFACTOR]
assignees:
  - jho951

body:
  - type: markdown
    attributes:
      value: |
        ### 설명
        ❗️유지보수 작업이나 리팩토링에 대한 간단한 설명을 작성해 주세요.

  - type: input
    attributes:
      label: 작업 설명
      description: 어떤 작업을 해야 하나요?
      placeholder: 수정할 부분이나 유지보수 작업에 대해 설명해주세요.
    validations:
      required: true

  - type: input
    attributes:
      label: 우선순위
      description: 이 작업의 우선순위는 무엇인가요?
      placeholder: 낮음, 중간, 높음
    validations:
      required: true

  - type: input
    attributes:
      label: 관련 이슈
      description: '관련된 이슈 번호가 있나요? (예: #123)'
      placeholder: '예: #123'
    validations:
      required: false